import { BWS_DATA, getAllData } from '@/helpers/api-util';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import ProductsPage from '@/components/ProductsPage/ProductsPage';

const AllProductsPage = (props: { products: BWS_DATA[] }) => {
  const router = useRouter();
  const { products } = props;
  return (
    <>
      <Head>
        <title>BWS - Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductsPage products={products} />
    </>
  );
};

export default AllProductsPage;

export const getStaticProps = async () => {
  const items = await getAllData();
  return {
    props: {
      products: items,
    },
    revalidate: 1800,
  };
};
